### PR TITLE
fix: portal SSR

### PR DESCRIPTION
**Pull request by atomiks**
@tyteen4a03  @tony 

Does this fix the issue?

### CODE REVIEW

**Comment by tony** [comment]
@atomiks Trying it out now.

**Comment by tony** [comment]
@atomiks How do I try it without having to publish it on NPM?

`yarn add atomiks/tippyjs-react#231/head`

```
failed Building production JavaScript and CSS bundles - 8.777s

 ERROR #98124  WEBPACK

Generating JavaScript bundles failed

Can't resolve '@tippyjs/react' in ''

If you're trying to use a package make sure that '@tippyjs/react' is installed. If you're trying to use a local file make sure that the path is correct.
```

**Comment by atomiks** [comment]
Edit `node_modules/@tippyjs/react/dist/tippy.umd.js` + `tippy.esm.js` with the new code.

**Comment by tony** [comment]
@atomiks Sure - but note it won't be a pushed build to production - it'll be a prod build on a local machine.

But this is probably enough.

`yarn add atomiks/tippyjs-react#231/head`
`cd node_modules@tippyjs/react`
`npm install`
`npm run build`

Works.

**Comment by tony** [comment]
Thank you @atomiks !

**Comment by atomiks** [comment]
Yeah it broke my docs website too and I didn't know why 😩 

I also just tested it on the docs (Gatsby) and it seems to work.

**Comment by tony** [comment]
@atomiks Gatsby seemed to bury the error for me.

next.js seemed to give a nicer traceback, interestingly

have a good weekend!

**Pull request merged**
